services:

  api:
    build: src/.
    container_name: cripto-api
    restart: unless-stopped
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    command: poetry run python3 main.py
    depends_on:
      - db
      - redis

  db:
    image: postgres:18-alpine
    container_name: cripto-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=${DB_HOST_AUTH_METHOD}
    volumes:
      - cripto_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cripto-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: src/.
    container_name: cripto-worker
    restart: unless-stopped
    volumes:
      - ./src:/app
    command: poetry run celery -A backend.tasks worker --queues=celery,job_0,job_1,job_2,job_3,job_4 --concurrency=8 --loglevel=info
    depends_on:
      - db
      - redis

volumes:
  cripto_db_data: