shared_buffers = 256MB
effective_cache_size = 768MB
work_mem = 16MB
maintenance_work_mem = 128MB
wal_buffers = 64MB
wal_compression = on
min_wal_size = 512MB
max_wal_size = 2GB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
max_connections = 100
random_page_cost = 1.1
effective_io_concurrency = 200
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
log_min_duration_statement = 500\